[start]
command:/usr/local/opnsense/scripts/devicemonitor/restart_service.py start
parameters:
type:script_output
message:starting device monitor service

[stop]
command:/usr/local/opnsense/scripts/devicemonitor/restart_service.py stop
parameters:
type:script_output
message:stopping device monitor service

[restart]
command:/usr/local/opnsense/scripts/devicemonitor/restart_service.py restart
parameters:
type:script_output
message:restarting device monitor service

[status]
command:/usr/local/opnsense/scripts/devicemonitor/restart_service.py status
parameters:
type:script_output
message:checking device monitor service status

[test]
command:/usr/local/opnsense/scripts/devicemonitor/test_connection.py
parameters:
type:script_output
message:testing device monitor connection